/* Java-GI - Java language bindings for GObject-Introspection-based libraries
 * Copyright (C) 2022-2026 Jan-Willem Harmannij
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

package org.javagi.base;

import org.gnome.glib.GLib;
import org.javagi.interop.Interop;

import java.lang.foreign.*;
import java.nio.charset.Charset;
import java.util.Arrays;
import java.util.Objects;

import static java.util.Objects.requireNonNull;

/**
 * A character string in the filesystem encoding.
 * <p>
 * GLib I/O-related functions use this for compatibility with non-utf8 encoded
 * filesystems. To display a Filename on-screen, convert it to a Java String
 * with {@link #toString()} or {@link #toString(Charset)}.
 * <p>
 * For more information, consult the GLib documentation on
 * <a href="https://docs.gtk.org/glib/character-set.html">character set conversions</a>.
 * <p>
 * Most Java methods generated by Java-GI that take Filename arguments are
 * overloaded for convenience with a method that accepts a String argument
 * instead of a Filename.
 */
public final class Filename {
    private final byte[] data;

    /**
     * Create a Filename object from a null-terminated filename in native memory.
     *
     * @param data     the null-terminated filename in native memory
     * @param transfer to free the native memory when ownership is transferred
     */
    public Filename(MemorySegment data, TransferOwnership transfer) {
        try (Arena arena = Arena.ofConfined()) {
            this.data = requireNonNull(Interop.getByteArrayFrom(data, arena, transfer));
        }
    }

    /**
     * Create a Filename object from a filename in native memory.
     *
     * @param data     the filename in native memory
     * @param size     the size of the filename
     * @param transfer to free the native memory when ownership is transferred
     */
    public Filename(MemorySegment data, long size, TransferOwnership transfer) {
        try (Arena arena = Arena.ofConfined()) {
            this.data = requireNonNull(Interop.getByteArrayFrom(data, size, arena, transfer));
        }
    }

    /**
     * Write the filename to native memory.
     *
     * @param alloc used to allocate the filename
     * @return the newly allocated memory segment with the filename
     */
    public MemorySegment toMemorySegment(SegmentAllocator alloc) {
        return Interop.allocateNativeArray(data, true, alloc);
    }

    /**
     * Create a Filename object from a Java String. The string is converted to
     * the native filesystem encoding with {@code g_filename_from_utf8()}.
     *
     * @param string the filename
     * @throws IllegalArgumentException when the string cannot be converted to
     *         the encoding of the filesystem. This can happen if {@code string}
     *         contains Japanese characters when the filesystem encoding is set
     *         to ISO-8859-1, for example.
     */
    public Filename(String string) {
        try {
            this.data = GLib.filenameFromUtf8(string, -1, null, null).data;
        } catch (GErrorException err) {
            throw new IllegalArgumentException(err);
        }
    }

    /**
     * Convert the filename to a Java String. The string is converted with
     * {@code g_filename_to_utf8()}.
     *
     * @return the filename
     * @throws IllegalArgumentException when the filename cannot be converted
     *         to utf8.
     */
    @Override
    public String toString() {
        try {
            return GLib.filenameToUtf8(this, data.length, null, null);
        } catch (GErrorException err) {
            throw new IllegalArgumentException(err);
        }
    }

    /**
     * Convert the filename to a Java String, using the provided Charset. The
     * string is converted with {@link String#String(byte[], Charset)}.
     *
     * @param charset the charset to decode the filename to a String
     * @return the filename
     */
    public String toString(Charset charset) {
        return new String(data, charset);
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Filename filename = (Filename) o;
        return Objects.deepEquals(data, filename.data);
    }

    @Override
    public int hashCode() {
        return Arrays.hashCode(data);
    }
}
