/**
 * This package contains Pointer types that represent a C pointer to a memory address.
 * The bindings generated by java-gi will use Pointer types when the native function
 * or field is an opaque pointer (for example gpointer or gconstpointer), or returns an
 * array of unknown length.
 */
package io.github.jwharm.javagi.pointer;