/* Java-GI - Java language bindings for GObject-Introspection-based libraries
 * Copyright (C) 2022-2024 the Java-GI developers
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

package io.github.jwharm.javagi.configuration;

/**
 * Defines the license note that is generated above every class file
 */
public final class LicenseNotice {

    public final static String NOTICE = """
            This file was automatically generated by Java-GI. Do not edit this file
            directly! Visit <https://github.com/jwharm/java-gi/> for more information.
            
            The API documentation in this file was derived from GObject-Introspection
            metadata and may include text or comments from the original C sources.
            
            Copyright (c), upstream authors as identified in the GObject-Introspection
            metadata.
            
            This generated file is distributed under the same license as the original
            GObject-Introspection data, unless otherwise specified. Users of this file
            are responsible for complying with any licenses or terms required by the
            original authors.
            
            THIS FILE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.
            """;
}
